tap "adoptopenjdk/openjdk"
tap "buo/cask-upgrade"
tap "dart-lang/dart"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
brew "openssl@3"
brew "libyaml"
brew "fastlane"
brew "fd"
brew "flyctl"
brew "fzf"
brew "gmp"
brew "gcc"
brew "git"
brew "make"
brew "mas"
brew "neovim"
brew "nvm"
brew "php"
brew "python@3.12"
brew "python@3.9"
brew "rbenv"
brew "ripgrep"
brew "stow"
brew "tree"
brew "unzip"
brew "wget"
brew "yarn"
brew "zoxide"
cask "1password"
cask "1password-cli"
cask "adguard"
cask "alfred"
cask "appcleaner"
cask "busycal"
cask "busycontacts"
cask "clop"
cask "font-jetbrains-mono-nerd-font"
cask "hyperkey"
cask "jordanbaird-ice"
cask "keyboard-maestro"
cask "lulu"
cask "mac-mouse-fix"
cask "spotify"
cask "swish"
cask "temurin@17"
cask "temurin@19"
cask "textsniper"
cask "wezterm"
cask "whisky"
mas "1Password for Safari", id: 1569813296
mas "Bear", id: 1091189122
mas "DevCleaner", id: 1388020431
mas "Dropover", id: 1355679052
mas "Klack", id: 6446206067
mas "Streaks", id: 963034692
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "Xcode", id: 497799835
