tap "adoptopenjdk/openjdk"
tap "dart-lang/dart"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "leoafarias/fvm"
brew "python@3.12"
brew "python@3.9"
brew "fastlane"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "git"
brew "go"
brew "imagemagick"
brew "lazygit"
brew "mas"
brew "neovim"
brew "rbenv"
brew "ripgrep"
brew "stow"
brew "tmux"
brew "tree"
brew "wget"
brew "yarn"
brew "zoxide"
cask "font-jetbrains-mono-nerd-font"
cask "temurin@17"
cask "wezterm"
mas "DevCleaner", id: 1388020431
mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "Xcode", id: 497799835
