[settings]
legacy_version_file = true
idiomatic_version_file_enable_tools = ["flutter"]

[tools]
ruby = "3"
node = "latest"
usage = "latest"
java = "17.0.0"
flutter = "latest"
dart = "latest"
lua-language-server = "latest"
stylua = "latest"
rust = "latest"
go = "latest"
python = "3"

[alias]
flutter = "asdf:nyuyuyu/asdf-flutter"
